---
swagger: "2.0"
info:
  description: Microservice implementation of CanDIG v1 federation
  version: 0.1.0
  title: CanDIG Federation API POC
  contact:
    email: dnaidoo@bcgsc.ca
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /federation
consumes:
- application/json
produces:
- application/json
schemes:
- http
paths:
  /search:
    get:
      summary: send query to a microservice
      description: |
        Entry point for Tyk to pass GET requests to CanDIG microservices. Federation broadcasting defined by 'federation' header.
      operationId: candig_federation.api.operations.get_search
      produces:
      - application/json
      parameters:
      - name: path
        in: query
        description: pass the path of the microservice to be queried
        required: true
        type: string
      - name: payload
        in: query
        description: arguements to be passed with GET request to microservice
        required: false
        type: string
      responses:
        "200":
          description: Successful query
        "400":
          description: Bad input parameter
        "403":
          description: Authorization Error
        "404":
          description: Expression not found
        "500":
          description: Internal Error
        "508":
          description: Federation node time out
    post:
      summary: Add entry to microservice
      description: |
        Entry point for Tyk to pass POST requests to CanDIG microservices. Federation broadcasting defined by 'federation' header.
      operationId: candig_federation.api.operations.post_search
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: post_microservice
        required: false
        schema:
          $ref: '#/definitions/PostSearch'
      responses:
        "201":
          description: entry created
        "400":
          description: invalid input, object invalid
        "403":
          description: Authorization Error
        "404":
          description: Expression not found
        "409":
          description: an existing item already exists
        "500":
          description: Internal Error
        "508":
          description: Federation node time out

  /announce:
    post:
      summary: Send node information to new node
      description: |
        Endpoint to announce existence to other nodes to validate peer lists
      operationId: candig_federation.api.operations.announce
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: annoucement
        required: true
        schema:
          $ref: '#/definitions/Announcement'
      responses:
        "200":
          description: Successful annoucement. Heartbeat initiated
        "500":
          description: Internal Error

  /heartbeat:
    get:
      summary: Receive notification that peers are alive
      description: |
        Endpoint to recieve a heartbeat from known peers
      operationId: candig_federation.api.operations.heartbeat
      responses:
        "200":
          description: Heartbeat received
        "500":
          description: Internal error


definitions:
  PostSearch:
    type: object
    required:
    - path
    - payload
    properties:
      path:
        type: string
        example: /v2/get
      payload:
        type: object
        additionalProperties: true
  Error:
    type: object
    required:
      - message
      - code
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  Announcement:
    type: object
    required:
    - peer
    - sender
    properties:
      peer:
        type: object
        example:  {peer: {url: 127.0.0.1:5000}}
        properties:
          url:
            type: string
      sender:
        type: object
        example:  {sender: {url: 127.0.0.1:5000}}
        properties:
          url:
            type: string
