language: python
dist: xenial   # required for Python >= 3.7
python:
  - "3.10"

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=candig_federation tests/ -vv

env:
  - TRAVIS=true # Used to skip local integration tests in test_local_federation.py