language: python
dist: focal   # required for Python >= 3.7
python:
  - "3.12"

install:
  - pip install -r requirements.txt

script:
  - mkdir config
  - pytest --cov=candig_federation tests/ -vv

env:
  - CONFIG_DIR=config TRAVIS=true # Used to skip local integration tests in test_local_federation.py